/* ============================================================
   ERP 2026 - FASE 1 - FUNDAÇÃO
   Arquivo: 002_domains.sql
   Descrição: Domínios (tipos personalizados) do banco
   ============================================================ */

/* === Domínios de identificação === */
CREATE DOMAIN DM_ID AS BIGINT NOT NULL;
CREATE DOMAIN DM_ID_NULL AS BIGINT;

/* === Domínios de texto === */
CREATE DOMAIN DM_NOME AS VARCHAR(100) NOT NULL;
CREATE DOMAIN DM_NOME_NULL AS VARCHAR(100);
CREATE DOMAIN DM_DESCRICAO AS VARCHAR(255);
CREATE DOMAIN DM_TEXTO AS BLOB SUB_TYPE TEXT;
CREATE DOMAIN DM_EMAIL AS VARCHAR(150);
CREATE DOMAIN DM_TELEFONE AS VARCHAR(20);
CREATE DOMAIN DM_CEP AS VARCHAR(10);
CREATE DOMAIN DM_UF AS CHAR(2);
CREATE DOMAIN DM_CNPJ_CPF AS VARCHAR(18);
CREATE DOMAIN DM_IE_RG AS VARCHAR(20);
CREATE DOMAIN DM_CODIGO AS VARCHAR(30);
CREATE DOMAIN DM_CAMINHO AS VARCHAR(500);

/* === Domínios numéricos === */
CREATE DOMAIN DM_QUANTIDADE AS NUMERIC(15,4) DEFAULT 0;
CREATE DOMAIN DM_VALOR AS NUMERIC(15,4) DEFAULT 0;
CREATE DOMAIN DM_PERCENTUAL AS NUMERIC(7,4) DEFAULT 0;
CREATE DOMAIN DM_INTEIRO AS INTEGER DEFAULT 0;

/* === Domínios de data/hora === */
CREATE DOMAIN DM_DATA AS DATE;
CREATE DOMAIN DM_DATAHORA AS TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

/* === Domínios booleanos === */
CREATE DOMAIN DM_BOOLEAN AS CHAR(1) DEFAULT 'N' CHECK (VALUE IN ('S', 'N'));

/* === Domínios de status === */
CREATE DOMAIN DM_STATUS AS CHAR(1) DEFAULT 'A' CHECK (VALUE IN ('A', 'I'));
CREATE DOMAIN DM_STATUS_DOC AS CHAR(1) DEFAULT 'P'
  CHECK (VALUE IN ('P', 'A', 'F', 'C'));
  /* P=Pendente, A=Aprovado, F=Faturado, C=Cancelado */
