/* ============================================================
   ERP 2026 - FASE 1 - FUNDAÇÃO
   Arquivo: 003_generators.sql
   Descrição: Generators (sequences) para auto-incremento
   ============================================================ */

CREATE GENERATOR GEN_EMPRESA_ID;
CREATE GENERATOR GEN_USUARIO_ID;
CREATE GENERATOR GEN_GRUPO_ID;
CREATE GENERATOR GEN_PERMISSAO_ID;
CREATE GENERATOR GEN_CLIENTE_ID;
CREATE GENERATOR GEN_FORNECEDOR_ID;
CREATE GENERATOR GEN_PRODUTO_ID;
CREATE GENERATOR GEN_CATEGORIA_ID;
CREATE GENERATOR GEN_ESTOQUE_ID;
CREATE GENERATOR GEN_MOVIMENTO_ESTOQUE_ID;
CREATE GENERATOR GEN_PEDIDO_VENDA_ID;
CREATE GENERATOR GEN_ITEM_PEDIDO_ID;
CREATE GENERATOR GEN_FINANCEIRO_ID;
CREATE GENERATOR GEN_CONTA_RECEBER_ID;
CREATE GENERATOR GEN_CONTA_PAGAR_ID;
CREATE GENERATOR GEN_CAIXA_ID;
CREATE GENERATOR GEN_MOVIMENTO_CAIXA_ID;
CREATE GENERATOR GEN_LOG_SISTEMA_ID;
CREATE GENERATOR GEN_CONFIGURACAO_ID;
CREATE GENERATOR GEN_UNIDADE_ID;
CREATE GENERATOR GEN_FORMA_PAGAMENTO_ID;
CREATE GENERATOR GEN_CONDICAO_PAGAMENTO_ID;
CREATE GENERATOR GEN_PARCELA_ID;
