/* ============================================================
   ERP 2026 - FASE 1 - FUNDAÇÃO
   Arquivo: 004_tables.sql
   Descrição: Criação de todas as tabelas do sistema
   ============================================================ */

/* ============================================================
   MÓDULO: SISTEMA / CONFIGURAÇÃO
   ============================================================ */

CREATE TABLE EMPRESA (
  ID              DM_ID PRIMARY KEY,
  RAZAO_SOCIAL    DM_NOME,
  NOME_FANTASIA   DM_NOME_NULL,
  CNPJ            DM_CNPJ_CPF,
  IE              DM_IE_RG,
  IM              DM_IE_RG,
  ENDERECO        VARCHAR(200),
  NUMERO          VARCHAR(10),
  COMPLEMENTO     VARCHAR(100),
  BAIRRO          VARCHAR(100),
  CIDADE          VARCHAR(100),
  UF              DM_UF,
  CEP             DM_CEP,
  TELEFONE        DM_TELEFONE,
  EMAIL           DM_EMAIL,
  LOGO            DM_CAMINHO,
  REGIME_TRIBUTARIO SMALLINT DEFAULT 1,
  /* 1=Simples Nacional, 2=Lucro Presumido, 3=Lucro Real */
  STATUS          DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA,
  CRT             SMALLINT DEFAULT 1
);

CREATE TABLE GRUPO (
  ID              DM_ID PRIMARY KEY,
  NOME            DM_NOME,
  DESCRICAO       DM_DESCRICAO,
  STATUS          DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA
);

CREATE TABLE USUARIO (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  GRUPO_ID        DM_ID_NULL,
  NOME            DM_NOME,
  LOGIN           VARCHAR(50) NOT NULL,
  SENHA           VARCHAR(255) NOT NULL,
  EMAIL           DM_EMAIL,
  TELEFONE        DM_TELEFONE,
  ADMINISTRADOR   DM_BOOLEAN DEFAULT 'N',
  STATUS          DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA,
  ULTIMO_ACESSO   DM_DATAHORA,
  TOKEN_RESET     VARCHAR(255),
  CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_USUARIO_GRUPO FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO(ID),
  CONSTRAINT UQ_USUARIO_LOGIN UNIQUE (LOGIN)
);

CREATE TABLE PERMISSAO (
  ID              DM_ID PRIMARY KEY,
  GRUPO_ID        DM_ID,
  MODULO          VARCHAR(50) NOT NULL,
  TELA            VARCHAR(50) NOT NULL,
  PODE_VISUALIZAR DM_BOOLEAN DEFAULT 'N',
  PODE_INSERIR    DM_BOOLEAN DEFAULT 'N',
  PODE_EDITAR     DM_BOOLEAN DEFAULT 'N',
  PODE_EXCLUIR    DM_BOOLEAN DEFAULT 'N',
  PODE_IMPRIMIR   DM_BOOLEAN DEFAULT 'N',
  CONSTRAINT FK_PERMISSAO_GRUPO FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO(ID)
);

CREATE TABLE CONFIGURACAO (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  CHAVE           VARCHAR(100) NOT NULL,
  VALOR           VARCHAR(500),
  DESCRICAO       DM_DESCRICAO,
  CONSTRAINT FK_CONFIG_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT UQ_CONFIG_CHAVE UNIQUE (EMPRESA_ID, CHAVE)
);

/* ============================================================
   MÓDULO: CADASTROS
   ============================================================ */

CREATE TABLE CATEGORIA (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  NOME            DM_NOME,
  DESCRICAO       DM_DESCRICAO,
  STATUS          DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA,
  CONSTRAINT FK_CATEGORIA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE UNIDADE (
  ID              DM_ID PRIMARY KEY,
  SIGLA           VARCHAR(6) NOT NULL,
  DESCRICAO       DM_DESCRICAO,
  CONSTRAINT UQ_UNIDADE_SIGLA UNIQUE (SIGLA)
);

CREATE TABLE CLIENTE (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  TIPO_PESSOA     CHAR(1) DEFAULT 'F' CHECK (VALUE IN ('F', 'J')),
  NOME            DM_NOME,
  NOME_FANTASIA   DM_NOME_NULL,
  CPF_CNPJ        DM_CNPJ_CPF,
  RG_IE           DM_IE_RG,
  ENDERECO        VARCHAR(200),
  NUMERO          VARCHAR(10),
  COMPLEMENTO     VARCHAR(100),
  BAIRRO          VARCHAR(100),
  CIDADE          VARCHAR(100),
  UF              DM_UF,
  CEP             DM_CEP,
  TELEFONE        DM_TELEFONE,
  CELULAR         DM_TELEFONE,
  EMAIL           DM_EMAIL,
  DATA_NASCIMENTO DM_DATA,
  LIMITE_CREDITO  DM_VALOR,
  OBSERVACOES     DM_TEXTO,
  STATUS          DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA,
  CONSTRAINT FK_CLIENTE_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE FORNECEDOR (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  TIPO_PESSOA     CHAR(1) DEFAULT 'J' CHECK (VALUE IN ('F', 'J')),
  RAZAO_SOCIAL    DM_NOME,
  NOME_FANTASIA   DM_NOME_NULL,
  CPF_CNPJ        DM_CNPJ_CPF,
  IE              DM_IE_RG,
  ENDERECO        VARCHAR(200),
  NUMERO          VARCHAR(10),
  COMPLEMENTO     VARCHAR(100),
  BAIRRO          VARCHAR(100),
  CIDADE          VARCHAR(100),
  UF              DM_UF,
  CEP             DM_CEP,
  TELEFONE        DM_TELEFONE,
  CELULAR         DM_TELEFONE,
  EMAIL           DM_EMAIL,
  CONTATO         VARCHAR(100),
  OBSERVACOES     DM_TEXTO,
  STATUS          DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA,
  CONSTRAINT FK_FORNECEDOR_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE PRODUTO (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  CATEGORIA_ID    DM_ID_NULL,
  FORNECEDOR_ID   DM_ID_NULL,
  UNIDADE_ID      DM_ID_NULL,
  CODIGO          DM_CODIGO,
  CODIGO_BARRAS   VARCHAR(20),
  DESCRICAO       DM_NOME,
  DESCRICAO_PDV   VARCHAR(40),
  NCM             VARCHAR(10),
  CEST            VARCHAR(9),
  CFOP_VENDA      VARCHAR(5),
  CFOP_COMPRA     VARCHAR(5),
  CST_ICMS        VARCHAR(5),
  CST_PIS         VARCHAR(5),
  CST_COFINS      VARCHAR(5),
  ALIQ_ICMS       DM_PERCENTUAL,
  ALIQ_PIS        DM_PERCENTUAL,
  ALIQ_COFINS     DM_PERCENTUAL,
  PRECO_CUSTO     DM_VALOR,
  PRECO_VENDA     DM_VALOR,
  MARGEM_LUCRO    DM_PERCENTUAL,
  ESTOQUE_MINIMO  DM_QUANTIDADE,
  ESTOQUE_MAXIMO  DM_QUANTIDADE,
  PESO_LIQUIDO    DM_QUANTIDADE,
  PESO_BRUTO      DM_QUANTIDADE,
  CONTROLA_ESTOQUE DM_BOOLEAN DEFAULT 'S',
  ATIVO           DM_STATUS,
  DATA_CADASTRO   DM_DATAHORA,
  IMAGEM          DM_CAMINHO,
  OBSERVACOES     DM_TEXTO,
  CONSTRAINT FK_PRODUTO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID),
  CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR(ID),
  CONSTRAINT FK_PRODUTO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES UNIDADE(ID)
);

/* ============================================================
   MÓDULO: ESTOQUE
   ============================================================ */

CREATE TABLE ESTOQUE (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  PRODUTO_ID      DM_ID,
  QUANTIDADE      DM_QUANTIDADE,
  CUSTO_MEDIO     DM_VALOR,
  DATA_ATUALIZACAO DM_DATAHORA,
  CONSTRAINT FK_ESTOQUE_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID),
  CONSTRAINT UQ_ESTOQUE_PROD UNIQUE (EMPRESA_ID, PRODUTO_ID)
);

CREATE TABLE MOVIMENTO_ESTOQUE (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  PRODUTO_ID      DM_ID,
  TIPO            CHAR(1) NOT NULL CHECK (VALUE IN ('E', 'S', 'A', 'I')),
  /* E=Entrada, S=Saída, A=Ajuste, I=Inventário */
  QUANTIDADE      DM_QUANTIDADE,
  CUSTO_UNITARIO  DM_VALOR,
  DOCUMENTO       VARCHAR(50),
  OBSERVACAO      DM_DESCRICAO,
  USUARIO_ID      DM_ID,
  DATA_MOVIMENTO  DM_DATAHORA,
  CONSTRAINT FK_MOVEST_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_MOVEST_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID),
  CONSTRAINT FK_MOVEST_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

/* ============================================================
   MÓDULO: VENDAS
   ============================================================ */

CREATE TABLE FORMA_PAGAMENTO (
  ID              DM_ID PRIMARY KEY,
  DESCRICAO       DM_NOME,
  TIPO            CHAR(2) DEFAULT 'DI',
  /* DI=Dinheiro, CC=Cartão Crédito, CD=Cartão Débito, CH=Cheque,
     BO=Boleto, PI=PIX, TR=Transferência */
  TEF             DM_BOOLEAN DEFAULT 'N',
  STATUS          DM_STATUS
);

CREATE TABLE CONDICAO_PAGAMENTO (
  ID              DM_ID PRIMARY KEY,
  DESCRICAO       DM_NOME,
  PARCELAS        DM_INTEIRO DEFAULT 1,
  DIAS_ENTRE_PARCELAS DM_INTEIRO DEFAULT 30,
  STATUS          DM_STATUS
);

CREATE TABLE PEDIDO_VENDA (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  CLIENTE_ID      DM_ID,
  USUARIO_ID      DM_ID,
  NUMERO          DM_INTEIRO,
  DATA_EMISSAO    DM_DATAHORA,
  DATA_ENTREGA    DM_DATA,
  STATUS          DM_STATUS_DOC,
  SUBTOTAL        DM_VALOR,
  DESCONTO        DM_VALOR,
  ACRESCIMO       DM_VALOR,
  TOTAL           DM_VALOR,
  FORMA_PAGAMENTO_ID DM_ID_NULL,
  CONDICAO_PAGAMENTO_ID DM_ID_NULL,
  OBSERVACOES     DM_TEXTO,
  CONSTRAINT FK_PEDIDO_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
  CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
  CONSTRAINT FK_PEDIDO_FORMAPAG FOREIGN KEY (FORMA_PAGAMENTO_ID) REFERENCES FORMA_PAGAMENTO(ID),
  CONSTRAINT FK_PEDIDO_CONDPAG FOREIGN KEY (CONDICAO_PAGAMENTO_ID) REFERENCES CONDICAO_PAGAMENTO(ID)
);

CREATE TABLE ITEM_PEDIDO (
  ID              DM_ID PRIMARY KEY,
  PEDIDO_VENDA_ID DM_ID,
  PRODUTO_ID      DM_ID,
  QUANTIDADE      DM_QUANTIDADE,
  VALOR_UNITARIO  DM_VALOR,
  DESCONTO        DM_VALOR,
  ACRESCIMO       DM_VALOR,
  VALOR_TOTAL     DM_VALOR,
  CFOP            VARCHAR(5),
  CST_ICMS        VARCHAR(5),
  ALIQ_ICMS       DM_PERCENTUAL,
  VALOR_ICMS      DM_VALOR,
  CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (PEDIDO_VENDA_ID) REFERENCES PEDIDO_VENDA(ID) ON DELETE CASCADE,
  CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);

/* ============================================================
   MÓDULO: FINANCEIRO
   ============================================================ */

CREATE TABLE FINANCEIRO (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  TIPO            CHAR(1) NOT NULL CHECK (VALUE IN ('R', 'P')),
  /* R=Receber, P=Pagar */
  CLIENTE_ID      DM_ID_NULL,
  FORNECEDOR_ID   DM_ID_NULL,
  PEDIDO_VENDA_ID DM_ID_NULL,
  DOCUMENTO       VARCHAR(50),
  DESCRICAO       DM_DESCRICAO,
  VALOR_ORIGINAL  DM_VALOR,
  VALOR_PAGO      DM_VALOR,
  VALOR_DESCONTO  DM_VALOR,
  VALOR_JUROS     DM_VALOR,
  VALOR_MULTA     DM_VALOR,
  DATA_EMISSAO    DM_DATAHORA,
  DATA_VENCIMENTO DM_DATA,
  DATA_PAGAMENTO  DM_DATA,
  STATUS          CHAR(1) DEFAULT 'A' CHECK (VALUE IN ('A', 'P', 'C', 'V')),
  /* A=Aberto, P=Pago, C=Cancelado, V=Vencido */
  FORMA_PAGAMENTO_ID DM_ID_NULL,
  OBSERVACOES     DM_TEXTO,
  CONSTRAINT FK_FIN_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_FIN_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
  CONSTRAINT FK_FIN_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR(ID),
  CONSTRAINT FK_FIN_PEDIDO FOREIGN KEY (PEDIDO_VENDA_ID) REFERENCES PEDIDO_VENDA(ID),
  CONSTRAINT FK_FIN_FORMAPAG FOREIGN KEY (FORMA_PAGAMENTO_ID) REFERENCES FORMA_PAGAMENTO(ID)
);

CREATE TABLE CONTA_RECEBER (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  FINANCEIRO_ID   DM_ID,
  PARCELA         DM_INTEIRO,
  VALOR           DM_VALOR,
  DATA_VENCIMENTO DM_DATA,
  DATA_RECEBIMENTO DM_DATA,
  VALOR_RECEBIDO  DM_VALOR,
  STATUS          CHAR(1) DEFAULT 'A' CHECK (VALUE IN ('A', 'P', 'C')),
  CONSTRAINT FK_CR_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_CR_FINANCEIRO FOREIGN KEY (FINANCEIRO_ID) REFERENCES FINANCEIRO(ID)
);

CREATE TABLE CONTA_PAGAR (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  FINANCEIRO_ID   DM_ID,
  PARCELA         DM_INTEIRO,
  VALOR           DM_VALOR,
  DATA_VENCIMENTO DM_DATA,
  DATA_PAGAMENTO  DM_DATA,
  VALOR_PAGO      DM_VALOR,
  STATUS          CHAR(1) DEFAULT 'A' CHECK (VALUE IN ('A', 'P', 'C')),
  CONSTRAINT FK_CP_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_CP_FINANCEIRO FOREIGN KEY (FINANCEIRO_ID) REFERENCES FINANCEIRO(ID)
);

/* ============================================================
   MÓDULO: CAIXA (PDV)
   ============================================================ */

CREATE TABLE CAIXA (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  USUARIO_ID      DM_ID,
  DATA_ABERTURA   DM_DATAHORA,
  DATA_FECHAMENTO DM_DATAHORA,
  VALOR_ABERTURA  DM_VALOR,
  VALOR_FECHAMENTO DM_VALOR,
  STATUS          CHAR(1) DEFAULT 'A' CHECK (VALUE IN ('A', 'F')),
  /* A=Aberto, F=Fechado */
  OBSERVACOES     DM_TEXTO,
  CONSTRAINT FK_CAIXA_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_CAIXA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE MOVIMENTO_CAIXA (
  ID              DM_ID PRIMARY KEY,
  CAIXA_ID        DM_ID,
  TIPO            CHAR(1) NOT NULL CHECK (VALUE IN ('E', 'S', 'G', 'P')),
  /* E=Entrada(Venda), S=Sangria, G=Suprimento, P=Pagamento */
  VALOR           DM_VALOR,
  DESCRICAO       DM_DESCRICAO,
  PEDIDO_VENDA_ID DM_ID_NULL,
  FORMA_PAGAMENTO_ID DM_ID_NULL,
  DATA_MOVIMENTO  DM_DATAHORA,
  CONSTRAINT FK_MOVCX_CAIXA FOREIGN KEY (CAIXA_ID) REFERENCES CAIXA(ID),
  CONSTRAINT FK_MOVCX_PEDIDO FOREIGN KEY (PEDIDO_VENDA_ID) REFERENCES PEDIDO_VENDA(ID),
  CONSTRAINT FK_MOVCX_FORMAPAG FOREIGN KEY (FORMA_PAGAMENTO_ID) REFERENCES FORMA_PAGAMENTO(ID)
);

/* ============================================================
   MÓDULO: AUDITORIA / LOGS
   ============================================================ */

CREATE TABLE LOG_SISTEMA (
  ID              DM_ID PRIMARY KEY,
  EMPRESA_ID      DM_ID,
  USUARIO_ID      DM_ID,
  TABELA          VARCHAR(50) NOT NULL,
  OPERACAO        CHAR(1) NOT NULL CHECK (VALUE IN ('I', 'U', 'D')),
  /* I=Insert, U=Update, D=Delete */
  REGISTRO_ID     BIGINT,
  DADOS_ANTERIORES DM_TEXTO,
  DADOS_NOVOS     DM_TEXTO,
  IP_ORIGEM       VARCHAR(45),
  DATA_HORA       DM_DATAHORA,
  CONSTRAINT FK_LOG_EMPRESA FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
  CONSTRAINT FK_LOG_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);
