/* ============================================================
   ERP 2026 - FASE 1 - FUNDAÇÃO
   Arquivo: 005_triggers.sql
   Descrição: Triggers de auto-incremento e regras de negócio
   ============================================================ */

/* === TRIGGERS DE AUTO-INCREMENTO === */

SET TERM ^ ;

CREATE TRIGGER TRG_EMPRESA_BI FOR EMPRESA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_EMPRESA_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_USUARIO_BI FOR USUARIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_USUARIO_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_GRUPO_BI FOR GRUPO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_GRUPO_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_PERMISSAO_BI FOR PERMISSAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_PERMISSAO_ID, 1);
END^

CREATE TRIGGER TRG_CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CLIENTE_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_FORNECEDOR_BI FOR FORNECEDOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_FORNECEDOR_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_PRODUTO_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_CATEGORIA_BI FOR CATEGORIA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CATEGORIA_ID, 1);
  IF (NEW.DATA_CADASTRO IS NULL) THEN
    NEW.DATA_CADASTRO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_UNIDADE_BI FOR UNIDADE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_UNIDADE_ID, 1);
END^

CREATE TRIGGER TRG_ESTOQUE_BI FOR ESTOQUE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_ESTOQUE_ID, 1);
  IF (NEW.DATA_ATUALIZACAO IS NULL) THEN
    NEW.DATA_ATUALIZACAO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_MOVIMENTO_ESTOQUE_BI FOR MOVIMENTO_ESTOQUE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_MOVIMENTO_ESTOQUE_ID, 1);
  IF (NEW.DATA_MOVIMENTO IS NULL) THEN
    NEW.DATA_MOVIMENTO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_PEDIDO_VENDA_BI FOR PEDIDO_VENDA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_PEDIDO_VENDA_ID, 1);
  IF (NEW.DATA_EMISSAO IS NULL) THEN
    NEW.DATA_EMISSAO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_ITEM_PEDIDO_BI FOR ITEM_PEDIDO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_ITEM_PEDIDO_ID, 1);
END^

CREATE TRIGGER TRG_FINANCEIRO_BI FOR FINANCEIRO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_FINANCEIRO_ID, 1);
  IF (NEW.DATA_EMISSAO IS NULL) THEN
    NEW.DATA_EMISSAO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_CONTA_RECEBER_BI FOR CONTA_RECEBER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CONTA_RECEBER_ID, 1);
END^

CREATE TRIGGER TRG_CONTA_PAGAR_BI FOR CONTA_PAGAR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CONTA_PAGAR_ID, 1);
END^

CREATE TRIGGER TRG_CAIXA_BI FOR CAIXA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CAIXA_ID, 1);
  IF (NEW.DATA_ABERTURA IS NULL) THEN
    NEW.DATA_ABERTURA = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_MOVIMENTO_CAIXA_BI FOR MOVIMENTO_CAIXA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_MOVIMENTO_CAIXA_ID, 1);
  IF (NEW.DATA_MOVIMENTO IS NULL) THEN
    NEW.DATA_MOVIMENTO = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_LOG_SISTEMA_BI FOR LOG_SISTEMA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_LOG_SISTEMA_ID, 1);
  IF (NEW.DATA_HORA IS NULL) THEN
    NEW.DATA_HORA = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TRG_CONFIGURACAO_BI FOR CONFIGURACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CONFIGURACAO_ID, 1);
END^

CREATE TRIGGER TRG_FORMA_PAGAMENTO_BI FOR FORMA_PAGAMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_FORMA_PAGAMENTO_ID, 1);
END^

CREATE TRIGGER TRG_CONDICAO_PAGAMENTO_BI FOR CONDICAO_PAGAMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_CONDICAO_PAGAMENTO_ID, 1);
END^

/* === TRIGGER DE ATUALIZAÇÃO DE ESTOQUE === */

CREATE TRIGGER TRG_MOVEST_AI FOR MOVIMENTO_ESTOQUE
ACTIVE AFTER INSERT POSITION 0
AS
DECLARE VARIABLE V_QTD NUMERIC(15,4);
BEGIN
  IF (NEW.TIPO = 'E' OR NEW.TIPO = 'A') THEN
    V_QTD = NEW.QUANTIDADE;
  ELSE IF (NEW.TIPO = 'S') THEN
    V_QTD = -NEW.QUANTIDADE;
  ELSE
    V_QTD = 0;

  UPDATE OR INSERT INTO ESTOQUE (EMPRESA_ID, PRODUTO_ID, QUANTIDADE, DATA_ATUALIZACAO)
    VALUES (NEW.EMPRESA_ID, NEW.PRODUTO_ID, :V_QTD, CURRENT_TIMESTAMP)
    MATCHING (EMPRESA_ID, PRODUTO_ID);

  /* Se o registro já existia, soma a quantidade */
  IF (ROW_COUNT = 0) THEN
    UPDATE ESTOQUE
      SET QUANTIDADE = QUANTIDADE + :V_QTD,
          DATA_ATUALIZACAO = CURRENT_TIMESTAMP
      WHERE EMPRESA_ID = NEW.EMPRESA_ID
        AND PRODUTO_ID = NEW.PRODUTO_ID;
END^

SET TERM ; ^
