/* ============================================================
   ERP 2026 - FASE 1 - FUNDAÇÃO
   Arquivo: 006_indexes.sql
   Descrição: Índices para performance
   ============================================================ */

/* === EMPRESA === */
CREATE INDEX IDX_EMPRESA_CNPJ ON EMPRESA(CNPJ);
CREATE INDEX IDX_EMPRESA_STATUS ON EMPRESA(STATUS);

/* === USUARIO === */
CREATE INDEX IDX_USUARIO_EMPRESA ON USUARIO(EMPRESA_ID);
CREATE INDEX IDX_USUARIO_GRUPO ON USUARIO(GRUPO_ID);
CREATE INDEX IDX_USUARIO_STATUS ON USUARIO(STATUS);

/* === PERMISSAO === */
CREATE INDEX IDX_PERMISSAO_GRUPO ON PERMISSAO(GRUPO_ID);
CREATE INDEX IDX_PERMISSAO_MODULO ON PERMISSAO(MODULO);

/* === CLIENTE === */
CREATE INDEX IDX_CLIENTE_EMPRESA ON CLIENTE(EMPRESA_ID);
CREATE INDEX IDX_CLIENTE_CPF_CNPJ ON CLIENTE(CPF_CNPJ);
CREATE INDEX IDX_CLIENTE_NOME ON CLIENTE(NOME);
CREATE INDEX IDX_CLIENTE_STATUS ON CLIENTE(STATUS);

/* === FORNECEDOR === */
CREATE INDEX IDX_FORNECEDOR_EMPRESA ON FORNECEDOR(EMPRESA_ID);
CREATE INDEX IDX_FORNECEDOR_CPF_CNPJ ON FORNECEDOR(CPF_CNPJ);
CREATE INDEX IDX_FORNECEDOR_RAZAO ON FORNECEDOR(RAZAO_SOCIAL);
CREATE INDEX IDX_FORNECEDOR_STATUS ON FORNECEDOR(STATUS);

/* === PRODUTO === */
CREATE INDEX IDX_PRODUTO_EMPRESA ON PRODUTO(EMPRESA_ID);
CREATE INDEX IDX_PRODUTO_CATEGORIA ON PRODUTO(CATEGORIA_ID);
CREATE INDEX IDX_PRODUTO_FORNECEDOR ON PRODUTO(FORNECEDOR_ID);
CREATE INDEX IDX_PRODUTO_CODIGO ON PRODUTO(CODIGO);
CREATE INDEX IDX_PRODUTO_BARRAS ON PRODUTO(CODIGO_BARRAS);
CREATE INDEX IDX_PRODUTO_DESCRICAO ON PRODUTO(DESCRICAO);
CREATE INDEX IDX_PRODUTO_NCM ON PRODUTO(NCM);
CREATE INDEX IDX_PRODUTO_ATIVO ON PRODUTO(ATIVO);

/* === CATEGORIA === */
CREATE INDEX IDX_CATEGORIA_EMPRESA ON CATEGORIA(EMPRESA_ID);

/* === ESTOQUE === */
CREATE INDEX IDX_ESTOQUE_EMPRESA ON ESTOQUE(EMPRESA_ID);
CREATE INDEX IDX_ESTOQUE_PRODUTO ON ESTOQUE(PRODUTO_ID);

/* === MOVIMENTO_ESTOQUE === */
CREATE INDEX IDX_MOVEST_EMPRESA ON MOVIMENTO_ESTOQUE(EMPRESA_ID);
CREATE INDEX IDX_MOVEST_PRODUTO ON MOVIMENTO_ESTOQUE(PRODUTO_ID);
CREATE INDEX IDX_MOVEST_DATA ON MOVIMENTO_ESTOQUE(DATA_MOVIMENTO);
CREATE INDEX IDX_MOVEST_TIPO ON MOVIMENTO_ESTOQUE(TIPO);

/* === PEDIDO_VENDA === */
CREATE INDEX IDX_PEDIDO_EMPRESA ON PEDIDO_VENDA(EMPRESA_ID);
CREATE INDEX IDX_PEDIDO_CLIENTE ON PEDIDO_VENDA(CLIENTE_ID);
CREATE INDEX IDX_PEDIDO_USUARIO ON PEDIDO_VENDA(USUARIO_ID);
CREATE INDEX IDX_PEDIDO_STATUS ON PEDIDO_VENDA(STATUS);
CREATE INDEX IDX_PEDIDO_DATA ON PEDIDO_VENDA(DATA_EMISSAO);

/* === ITEM_PEDIDO === */
CREATE INDEX IDX_ITEM_PEDIDO ON ITEM_PEDIDO(PEDIDO_VENDA_ID);
CREATE INDEX IDX_ITEM_PRODUTO ON ITEM_PEDIDO(PRODUTO_ID);

/* === FINANCEIRO === */
CREATE INDEX IDX_FIN_EMPRESA ON FINANCEIRO(EMPRESA_ID);
CREATE INDEX IDX_FIN_CLIENTE ON FINANCEIRO(CLIENTE_ID);
CREATE INDEX IDX_FIN_FORNECEDOR ON FINANCEIRO(FORNECEDOR_ID);
CREATE INDEX IDX_FIN_TIPO ON FINANCEIRO(TIPO);
CREATE INDEX IDX_FIN_STATUS ON FINANCEIRO(STATUS);
CREATE INDEX IDX_FIN_VENCIMENTO ON FINANCEIRO(DATA_VENCIMENTO);

/* === CONTA_RECEBER === */
CREATE INDEX IDX_CR_EMPRESA ON CONTA_RECEBER(EMPRESA_ID);
CREATE INDEX IDX_CR_FINANCEIRO ON CONTA_RECEBER(FINANCEIRO_ID);
CREATE INDEX IDX_CR_VENCIMENTO ON CONTA_RECEBER(DATA_VENCIMENTO);
CREATE INDEX IDX_CR_STATUS ON CONTA_RECEBER(STATUS);

/* === CONTA_PAGAR === */
CREATE INDEX IDX_CP_EMPRESA ON CONTA_PAGAR(EMPRESA_ID);
CREATE INDEX IDX_CP_FINANCEIRO ON CONTA_PAGAR(FINANCEIRO_ID);
CREATE INDEX IDX_CP_VENCIMENTO ON CONTA_PAGAR(DATA_VENCIMENTO);
CREATE INDEX IDX_CP_STATUS ON CONTA_PAGAR(STATUS);

/* === CAIXA === */
CREATE INDEX IDX_CAIXA_EMPRESA ON CAIXA(EMPRESA_ID);
CREATE INDEX IDX_CAIXA_USUARIO ON CAIXA(USUARIO_ID);
CREATE INDEX IDX_CAIXA_STATUS ON CAIXA(STATUS);
CREATE INDEX IDX_CAIXA_DATA ON CAIXA(DATA_ABERTURA);

/* === MOVIMENTO_CAIXA === */
CREATE INDEX IDX_MOVCX_CAIXA ON MOVIMENTO_CAIXA(CAIXA_ID);
CREATE INDEX IDX_MOVCX_TIPO ON MOVIMENTO_CAIXA(TIPO);
CREATE INDEX IDX_MOVCX_DATA ON MOVIMENTO_CAIXA(DATA_MOVIMENTO);

/* === LOG_SISTEMA === */
CREATE INDEX IDX_LOG_EMPRESA ON LOG_SISTEMA(EMPRESA_ID);
CREATE INDEX IDX_LOG_USUARIO ON LOG_SISTEMA(USUARIO_ID);
CREATE INDEX IDX_LOG_TABELA ON LOG_SISTEMA(TABELA);
CREATE INDEX IDX_LOG_DATA ON LOG_SISTEMA(DATA_HORA);
