/* ============================================================
   ERP 2026 - FASE 1 - FUNDAÇÃO
   Arquivo: 007_initial_data.sql
   Descrição: Dados iniciais obrigatórios para funcionamento
   ============================================================ */

/* === Unidades de Medida padrão === */
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('UN', 'Unidade');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('KG', 'Quilograma');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('LT', 'Litro');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('MT', 'Metro');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('CX', 'Caixa');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('PC', 'Peça');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('PAR', 'Par');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('PCT', 'Pacote');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('FD', 'Fardo');
INSERT INTO UNIDADE (SIGLA, DESCRICAO) VALUES ('M2', 'Metro Quadrado');

/* === Formas de Pagamento padrão === */
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('Dinheiro', 'DI', 'A');
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('Cartão de Crédito', 'CC', 'A');
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('Cartão de Débito', 'CD', 'A');
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('PIX', 'PI', 'A');
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('Boleto', 'BO', 'A');
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('Cheque', 'CH', 'A');
INSERT INTO FORMA_PAGAMENTO (DESCRICAO, TIPO, STATUS) VALUES ('Transferência', 'TR', 'A');

/* === Condições de Pagamento padrão === */
INSERT INTO CONDICAO_PAGAMENTO (DESCRICAO, PARCELAS, DIAS_ENTRE_PARCELAS, STATUS) VALUES ('À Vista', 1, 0, 'A');
INSERT INTO CONDICAO_PAGAMENTO (DESCRICAO, PARCELAS, DIAS_ENTRE_PARCELAS, STATUS) VALUES ('30 dias', 1, 30, 'A');
INSERT INTO CONDICAO_PAGAMENTO (DESCRICAO, PARCELAS, DIAS_ENTRE_PARCELAS, STATUS) VALUES ('30/60 dias', 2, 30, 'A');
INSERT INTO CONDICAO_PAGAMENTO (DESCRICAO, PARCELAS, DIAS_ENTRE_PARCELAS, STATUS) VALUES ('30/60/90 dias', 3, 30, 'A');
INSERT INTO CONDICAO_PAGAMENTO (DESCRICAO, PARCELAS, DIAS_ENTRE_PARCELAS, STATUS) VALUES ('2x sem juros', 2, 30, 'A');
INSERT INTO CONDICAO_PAGAMENTO (DESCRICAO, PARCELAS, DIAS_ENTRE_PARCELAS, STATUS) VALUES ('3x sem juros', 3, 30, 'A');

/* === Grupo Administrador padrão === */
INSERT INTO GRUPO (NOME, DESCRICAO, STATUS) VALUES ('Administradores', 'Acesso total ao sistema', 'A');

/* === Empresa padrão (para primeiro uso) === */
INSERT INTO EMPRESA (RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, IE, ENDERECO, NUMERO, BAIRRO, CIDADE, UF, CEP, STATUS, REGIME_TRIBUTARIO)
  VALUES ('EMPRESA DEMONSTRACAO LTDA', 'ERP DEMO', '00.000.000/0001-00', 'ISENTO', 'Rua Exemplo', '100', 'Centro', 'São Paulo', 'SP', '01000-000', 'A', 1);

/* === Usuário Administrador padrão === */
/* Senha: admin123 (deve ser trocada no primeiro acesso) */
/* NOTA: Em produção, a senha deve ser hash SHA-256 ou bcrypt */
INSERT INTO USUARIO (EMPRESA_ID, GRUPO_ID, NOME, LOGIN, SENHA, EMAIL, ADMINISTRADOR, STATUS)
  VALUES (1, 1, 'Administrador', 'admin', 'admin123', 'admin@empresa.com', 'S', 'A');

/* === Permissões completas para grupo Administrador === */
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'CADASTROS', 'CLIENTES', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'CADASTROS', 'FORNECEDORES', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'CADASTROS', 'PRODUTOS', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'ESTOQUE', 'MOVIMENTACAO', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'VENDAS', 'PEDIDOS', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'FINANCEIRO', 'CONTAS', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'CAIXA', 'PDV', 'S', 'S', 'S', 'S', 'S');
INSERT INTO PERMISSAO (GRUPO_ID, MODULO, TELA, PODE_VISUALIZAR, PODE_INSERIR, PODE_EDITAR, PODE_EXCLUIR, PODE_IMPRIMIR)
  VALUES (1, 'SISTEMA', 'CONFIGURACOES', 'S', 'S', 'S', 'S', 'S');
