/* ============================================================
   ERP 2026 - Scripts adicionais (Fases 3-9)
   Tabelas e campos adicionais necessários
   ============================================================ */

/* Adicionar campo NUMERO_NFE e CHAVE_NFE ao PEDIDO_VENDA */
ALTER TABLE PEDIDO_VENDA ADD NUMERO_NFE INTEGER;
ALTER TABLE PEDIDO_VENDA ADD CHAVE_NFE VARCHAR(50);
ALTER TABLE PEDIDO_VENDA ADD NUMERO INTEGER;

/* Tabela MOVIMENTO_CAIXA (complementar) */
CREATE TABLE MOVIMENTO_CAIXA (
    ID BIGINT NOT NULL,
    CAIXA_ID BIGINT NOT NULL,
    TIPO CHAR(1) NOT NULL, /* V=Venda, S=Sangria, E=Suprimento */
    VALOR NUMERIC(15,2) NOT NULL,
    DESCRICAO VARCHAR(200),
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MOVIMENTO_CAIXA PRIMARY KEY (ID),
    CONSTRAINT FK_MOVCX_CAIXA FOREIGN KEY (CAIXA_ID) REFERENCES CAIXA(ID)
);

CREATE GENERATOR GEN_MOVIMENTO_CAIXA_ID;

SET TERM !! ;
CREATE TRIGGER TRG_MOVIMENTO_CAIXA_BI FOR MOVIMENTO_CAIXA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
        NEW.ID = GEN_ID(GEN_MOVIMENTO_CAIXA_ID, 1);
END!!
SET TERM ; !!

/* Índices adicionais para performance */
CREATE INDEX IDX_MOVCX_CAIXA ON MOVIMENTO_CAIXA (CAIXA_ID);
CREATE INDEX IDX_MOVCX_TIPO ON MOVIMENTO_CAIXA (TIPO);
CREATE INDEX IDX_PV_STATUS ON PEDIDO_VENDA (STATUS);
CREATE INDEX IDX_PV_NUMERO ON PEDIDO_VENDA (NUMERO);
CREATE INDEX IDX_CR_STATUS ON CONTA_RECEBER (STATUS);
CREATE INDEX IDX_CR_VENC ON CONTA_RECEBER (DATA_VENCIMENTO);
CREATE INDEX IDX_CP_STATUS ON CONTA_PAGAR (STATUS);
CREATE INDEX IDX_CP_VENC ON CONTA_PAGAR (DATA_VENCIMENTO);
CREATE INDEX IDX_ME_TIPO ON MOVIMENTO_ESTOQUE (TIPO);

COMMIT;
